# Generated by Django 2.2 on 2020-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=5, null=True)),
                ('categories', models.CharField(blank=True, max_length=25, null=True)),
                ('item_id', models.CharField(blank=True, max_length=9, null=True)),
                ('english_name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.FloatField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
