# Generated by Django 2.2 on 2020-05-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='category_id',
            new_name='CATEGORY_ID',
        ),
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
