# Generated by Django 2.2 on 2020-05-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0002_auto_20200520_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='categories',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='english_name',
            new_name='ENGLISH_NAME',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='item_id',
            new_name='ITEM_ID',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='price',
            new_name='PRICE',
        ),
    ]
